### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mfnalex** [Chereza/TreeTwerk-remastered#3]
Hey :)

Your code is kind of messy. I made a cleaned up maven version, you can view it here:

https://github.com/JEFF-Media-GbR/TreeTwerk-remastered

Greetings!

**Comment by Cazcez** [comment]
Thanks for helping us!
Do u have discord or a mail for talking? (i prefer discord)

**Comment by mfnalex** [comment]
mfnalex#1908
